routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('welcome');

});

Auth::routes();

Route::get('/home', 'HomeController@index')->name('home');

Route::resource('orderdata', 'OrderdataController');

app/Orderdata.php
<?php
namespace App;
use Illuminate\Database\Eloquent\Model;
class Orderdata extends Model{
    public function User()
    
    {
        return $this->belongsToMany('App\User');
    }
    
    public function Order_Type()

    {
        return $this->belongsToMany('App\Order_Type');
    }

    public function Order_Line()

    {
        return $this->belongsToMany('App\Order_Line');
    }


    protected $fillable = [
        'User_id','Type_id','Manage_id','datetime', 'total_price',
        ];
    }

app/Http/Controllers/OrderdataController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;
use App\Orderdata;

class OrderdataController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $orders = Orderdata::latest()->paginate(5);
        return view('orderdata.index', compact('orders'))
                  ->with('i', (request()->input('page',1) -1)*5);
    }
    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        return view('Orderdata.create');
    }
    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        $request->validate([
          'User_id'     => 'required',
          'Type_id'     => 'required',
          'Manage_id'   => 'required',
          'datetime'    => 'required',
          'total_price' => 'required'
        ]);
        Orderdata::create($request->all());
        return redirect()->route('orderdata.index')
                        ->with('success', 'new order created successfully');
    }
    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        $orderdata= Orderdata::find($id);
        return view('orderdata.detail', compact('orderdata'));
    }
    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        $orderdata = Orderdata::find($id);
        return view('orderdata.edit', compact('orderdata'));
    }
    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
      $request->validate([
        'datetime' => 'required',
        'total_price' => 'required'
      ]);
      $orderdata = Orderdata::find($id);
      $orderdata->datetime = $request->get('datetime');
      $orderdata->total_price = $request->get('total_price');
      $orderdata->save();
      return redirect()->route('orderdata.index')
                      ->with('success', 'Order  updated successfully');
    }
    /*
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        $orderdata = Orderdata::find($id);
        $orderdata->delete();
        return redirect()->route('orderdata.index')
                        ->with('success', 'order deleted successfully');
    }
}

resources/views/orderdata/create.blade.php
@extends('layouts.app')
@section('content')
  <div class="container">
    <div class="row">
      <div class="col-lg-12">
        <h3>test</h3>
      </div>
    </div>

    @if ($errors->any())
      <div class="alert alert-danger">
        <strong>Whoops! </strong> there where some problems with your input.<br>
        <ul>
          @foreach ($errors as $error)
            <li>{{$error}}</li>
          @endforeach
        </ul>
      </div>
    @endif

    <form action="{{route('orderdata.store')}}" method="post">
      @csrf
      <div class="row">
        <div class="col-md-12">
          <strong>Datum en tijd :</strong>
          <input type="datetime-local" name="datetime" class="form-control" placeholder="vul hier je datum en tijd in">
        </div>
        <div class="col-md-12">
          <strong>totaal_prijs :</strong>
          <input type="number" name="total_price" class="form-control" placeholder="totaal_prijs">
        </div>

        <div class="col-md-12">
          <a href="{{route('orderdata.index')}}" class="btn btn-sm btn-success">Back</a>
          <button type="submit" class="btn btn-sm btn-primary">Submit</button>
        </div>
      </div>
    </form>

  </div>
@endsection

resources/views/orderdata/detail.blade.php
@extends('layouts.app')
@section('content')
  <div class="container">
    <div class="row">
      <div class="col-md-12">
        <h3>test</h3>
        <hr>
      </div>
    </div>
    <div class="row">
      <div class="col-md-12">
        <div class="form-group">
          <strong>Datum en tijd : </strong> {{$orderdata->datetime}}
        </div>
      </div>
      <div class="col-md-12">
        <div class="form-group">
          <strong> totaal_prijs: </strong> {{$orderdata->total_price}}
        </div>
      </div>
      <div class="col-md-12">
        <a href="{{route('orderdata.index')}}" class="btn btn-sm btn-success">Back</a>
      </div>
    </div>
  </div>
@endsection

resources/views/orderdata/edit.blade.php
@extends('layouts.app')
@section('content')
  <div class="container">
    <div class="row">
      <div class="col-lg-12">
        <h3>test</h3>
      </div>
    </div>

    @if ($errors->any())
      <div class="alert alert-danger">
        <strong>Whoops! </strong> there where some problems with your input.<br>
        <ul>
          @foreach ($errors as $error)
            <li>{{$error}}</li>
          @endforeach
        </ul>
      </div>
    @endif

    <form action="{{route('orderdata.update',$orderdata->id)}}" method="post">
      @csrf
      @method('PUT')
      <div class="row">
        <div class="col-md-12">
          <strong>Datum en Tijd :</strong>
          <input type="text" name="datetime" class="form-control" value="{{$orderdata->datetime}}">
        </div>
        <div class="col-md-12">
          <strong>totaal_prijs :</strong>
          <textarea class="form-control" name="total_price" rows="8" cols="80">{{$orderdata->total_price}}</textarea>
        </div>

        <div class="col-md-12">
          <a href="{{route('orderdata.index')}}" class="btn btn-sm btn-success">Back</a>
          <button type="submit" class="btn btn-sm btn-primary">Submit</button>
        </div>
      </div>
    </form>
  </div>
@endsection

resources/views/orderdata/index.blade.php
@extends('layouts.app')
@section('content')

  <div class="container">
    <div class="row">
      <div class="col-md-10">
        <h3>test</h3>
      </div>
      <div class="col-sm-2">
        <a class="btn btn-sm btn-success" href="{{ route('orderdata.create') }}">Maak een nieuwe order aan</a>
      </div>
    </div>

    @if ($message = Session::get('success'))
      <div class="alert alert-success">
        <p>{{$message}}</p>
      </div>
    @endif

    <table class="table table-hover table-sm">
      <tr>
        <th width = "50px"><b>No.</b></th>
        <th width = "300px">datum en tijd</th>
        <th>totaal_prijs</th>
        <th width = "180px">Action</th>
      </tr>

      @foreach ($orders as $orderdata)
        <tr>
          <td><b>{{++$i}}.</b></td>
          <td>{{$orderdata->datetime}}</td>
          <td>{{$orderdata->total_price}}</td>
          <td>
            <form action="{{ route('orderdata.destroy', $orderdata->id) }}" method="post">
              <a class="btn btn-sm btn-success" href="{{route('orderdata.show',$orderdata->id)}}">Show</a>
              <a class="btn btn-sm btn-warning" href="{{route('orderdata.edit',$orderdata->id)}}">Edit</a>
              @csrf
              @method('DELETE')
              <button type="submit" class="btn btn-sm btn-danger">Delete</button>
            </form>
          </td>
        </tr>
      @endforeach
    </table>

{!! $orders->links() !!}
  </div>
@endsection